my_str = "  Hello, World!  "
print(my_str.strip())
print(my_str.lower())
print(my_str.upper())
print(my_str.replace("Hello", "Hi"))
print(my_str.split(","))
print(my_str.find("World"))
print(my_str.count("l"))

my_list = [1, 2, 3, 4, 2]
my_list.append(5)
print(my_list)
my_list.insert(2, 10)
print(my_list)
my_list.remove(2)
print(my_list)
my_list.pop()
print(my_list)
print(my_list.index(10))
print(my_list.count(2))
my_list.reverse()
print(my_list)
my_list.sort()
print(my_list)

my_tuple = (1, 2, 3, 2, 4)
print(my_tuple.count(2))
print(my_tuple.index(3))

my_set = {1, 2, 3}
my_set.add(4)
print(my_set)
my_set.update([5, 6])
print(my_set)
my_set.remove(2)
print(my_set)
my_set.discard(10)
print(my_set)
my_set.pop()
print(my_set)
my_set.clear()
print(my_set)

my_dict = {"name": "Shreeyon", "age": 20, "city": "Ktm"}
print(my_dict.get("name"))
print(my_dict.keys())
print(my_dict.values())
print(my_dict.items())
my_dict.update({"age": 21})
print(my_dict)
my_dict.pop("city")
print(my_dict)
my_dict.clear()
print(my_dict)
